#define PS2_BIT_CNT                 r18
#define PS2_RECV_VAL                r19
#define PS2_BYTE_CNT                r20
#define PS2_RECV_READY              r21

#define PS2_BUFFER_SIZE             3


#define PS2_CMD_RESET               0xFF
#define PS2_CMD_SET_DEFAULTS        0xF6
#define PS2_CMD_EN_DATA_REPORTING   0xF4
#define PS2_CMD_SET_REMOTE_MODE     0xF0
#define PS2_CMD_SET_STREAM_MODE     0xEA
#define PS2_ACK                     0xFA
